#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Apr  9 13:47:29 2018
@author: angli

This is to prepare all the links that need to be download from Wikidump

"""

if __name__ == "__main__":

    outString = ''
    
    for y in range(2013, 2016): 
        year = '{num:04d}'.format(num=y)
        for m in range(1, 13):
            month = '{num:02d}'.format(num=m)
            for d in range(1,31):
                date = '{num:02d}'.format(num=d)
                for h in range(24):
                    hour = '{num:02d}'.format(num=h)
                    ymd = year+month+date
                
                    download_str = "https://dumps.wikimedia.org/other/pagecounts-raw/{}/{}-{}/pagecounts-{}-{}0000.gz".format(year, year, month, ymd,hour)
                    outString += download_str
                    outString += '\n'
    
    with open('/Users/angli/ANG/OneDrive/Documents/Pitt_PhD/ResearchProjects/Wiki_Event/Wikidump.txt', 'w') as f:
        f.write(outString)
        f.close()
    
    #wget -i text_file.txt